### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xBlackeN** [MWHunter/KohiKB#6]
I have an issue,
when i try to start server it just says in console: (2.0.1 is the latest version)
[17:05:33] [Server thread/ERROR]: Error occurred while enabling KohiKB v2.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/KohiKB-2.0.1.jar

**Comment by MWHunter** [comment]
Fixed by 7da0a19
