### ISSUE TITLE
fall knockback

### ISSUE THREAD

**Issue by NewPixelDev** [MWHunter/KohiKB#7]
It's good, but the thing is, when you take fall damage, it sometimes sees it as player damage, so if a player gets hit and then they take fall damage, then they will take KB sideways, which in a Bedwars game, will push them off the bridge.

This problem still exists, please fix

**Comment by MWHunter** [comment]
You sure you aren't using an old version of OldCombatMechanics?

**Comment by NewPixelDev** [comment]
I am not using OldCombatMechanics
I am currently using
LegacyKB Version 2.2
paper-1.8.8-445

Can this problem be fixed? Be grateful if you can.

**Comment by MWHunter** [comment]
Try compiling the latest git version

**Comment by MWHunter** [comment]
closing as no response after a month

**Comment by NewPixelDev** [comment]
Yes you managed to fix the problem thanks!
